###
GET http://localhost:3000/hi
Accept: application/json
Content-Type: application/json
Authorization: Bearer

###
POST http://localhost:3000/api/auth/register
Accept: application/json
Content-Type: application/json

{
  "username": "jamal",
  "password": "jamal123",
  "email": "jamal@example.com"
}

###
POST http://localhost:3000/api/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "jamal",
  "password": "jamal123"
}

###
GET http://localhost:3000/api/admins
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiVXNlck5hbWUiOiJqYW1hbCIsImlzcyI6ImtvcmllYnJ1aCIsImV4cCI6MTczMTIyNDUwN30.5XoKUATZa9rXaV-4wlD4ns5-jaF7cI7u0Yqu6qdtn9I

###
POST http://localhost:3000//api/auth/logout
Accept: application/json
Content-Type: application/json

