### LOGIN GET TOKEN
POST http://localhost:3000/api/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "korie",
  "password": "korie123"
}

### CREATE
POST http://localhost:3000/api/items
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiVXNlck5hbWUiOiJrb3JpZSIsImlzcyI6ImtvcmllYnJ1aCIsImV4cCI6MTczMTA4NTc0OH0.aiH-2NK9LHN8Z3ErnL_kApywGZx9zSLo3fceziBA4Ug

{
  "name": "Iphone 12x",
  "description": "Limited edition for jamal Only",
  "price": 32000000,
  "quantity": 3,
  "category_id": 1,
  "supplier_id": 1
}

### FINDALL
GET http://localhost:3000/api/items
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiVXNlck5hbWUiOiJrb3JpZSIsImlzcyI6ImtvcmllYnJ1aCIsImV4cCI6MTczMTEwNDk1MX0.HoXWgz5vB9XxPgOKpG2DLnTgj2ZOWgXFi3Bq0ji9KFg

### SUMARY
GET http://localhost:3000/api/items/info
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiVXNlck5hbWUiOiJrb3JpZSIsImlzcyI6ImtvcmllYnJ1aCIsImV4cCI6MTczMTEwNDk1MX0.HoXWgz5vB9XxPgOKpG2DLnTgj2ZOWgXFi3Bq0ji9KFg

### FIND BY CONDITION
GET http://localhost:3000/api/items/condition?condition=under&threshold=4
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiVXNlck5hbWUiOiJrb3JpZSIsImlzcyI6ImtvcmllYnJ1aCIsImV4cCI6MTczMTEwNDk1MX0.HoXWgz5vB9XxPgOKpG2DLnTgj2ZOWgXFi3Bq0ji9KFg

### FIND BY CONDITION
GET http://localhost:3000/api/items/condition?condition=over&threshold=4
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiVXNlck5hbWUiOiJrb3JpZSIsImlzcyI6ImtvcmllYnJ1aCIsImV4cCI6MTczMTEwMjYzOX0.5jcRRl068HmcVWxdeZHytRNwEwPi75FvHKZktr_70y4

### FIND BY CONDITION
GET http://localhost:3000/api/items/condition?condition=equal&threshold=10
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiVXNlck5hbWUiOiJrb3JpZSIsImlzcyI6ImtvcmllYnJ1aCIsImV4cCI6MTczMTEwMjYzOX0.5jcRRl068HmcVWxdeZHytRNwEwPi75FvHKZktr_70y4