
###
GET http://localhost:3000/hi
Accept: application/json
Content-Type: application/json

###
POST http://localhost:3000/api/auth/register
Accept: application/json
Content-Type: application/json

{
  "username": "fatlem",
  "password": "fatlem224",
  "email": "fatlem@example.com"
}

###
POST http://localhost:3000/api/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "fatlem",
  "password": "fatlem224S"
}


###
GET http://localhost:3000/api/admins
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiVXNlck5hbWUiOiJmYXRsZW0iLCJpc3MiOiJrb3JpZWJydWgiLCJleHAiOjE3MzEyNTE4MDh9.m8Vvsnz2ylbnYhB10I59Bv6udGgo5yHlkppF4R-veoA

###
POST http://localhost:3000//api/auth/logout
Accept: application/json
Content-Type: application/json

