### LOGIN FIRST
POST http://localhost:3000/api/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}

###
POST http://localhost:3000/api/categories
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiVXNlck5hbWUiOiJhZG1pbiIsImlzcyI6ImtvcmllYnJ1aCIsImV4cCI6MTczMzA2OTU3MH0.Cn0QgC4rL7tD3TP7phRrFXCDpqd7664GuhOdjin_oco

{
  "name": "YOSH",
  "description": "Laptop Gaming"
}


###
GET http://localhost:3000/api/categories
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiVXNlck5hbWUiOiJhZG1pbiIsImlzcyI6ImtvcmllYnJ1aCIsImV4cCI6MTczMzA2OTkzMn0.X-9-Joea7cjMEoYyOYn7hvTXuyvmlHBf0VmEmuc-XCM


###
GET http://localhost:3000/api/categories/info
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiVXNlck5hbWUiOiJhZG1pbiIsImlzcyI6ImtvcmllYnJ1aCIsImV4cCI6MTczMzA2OTkzMn0.X-9-Joea7cjMEoYyOYn7hvTXuyvmlHBf0VmEmuc-XCM


