### LOGIN FIRST
POST http://localhost:3000/api/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "fatlem",
  "password": "fatlem224"
}

###
POST http://localhost:3000/api/categories
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiVXNlck5hbWUiOiJmYXRsZW0iLCJpc3MiOiJrb3JpZWJydWgiLCJleHAiOjE3MzEyNTMyNDl9.Qy6Y5sUSazZkEbzosep9GRzKvUXYGpjLzLEdSKQbecM

{
  "name": "Elektronik",
  "description": "Laptop Gaming"
}


###
GET http://localhost:3000/api/categories
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiVXNlck5hbWUiOiJmYXRsZW0iLCJpc3MiOiJrb3JpZWJydWgiLCJleHAiOjE3MzEyNTMyNDl9.Qy6Y5sUSazZkEbzosep9GRzKvUXYGpjLzLEdSKQbecM


###
GET http://localhost:3000/api/categories/info
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiVXNlck5hbWUiOiJmYXRsZW0iLCJpc3MiOiJrb3JpZWJydWgiLCJleHAiOjE3MzEyNTMyNDl9.Qy6Y5sUSazZkEbzosep9GRzKvUXYGpjLzLEdSKQbecM


