### LOGIN GET TOKEN
POST http://localhost:3000/api/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}

### CREATE
POST http://localhost:3000/api/items
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiVXNlck5hbWUiOiJhZG1pbiIsImlzcyI6ImtvcmllYnJ1aCIsImV4cCI6MTczMzA3MDQ5Nn0.3NxI_XKyccMhGIbAfm8HaxQenWhHz0z3L35GYpIS5A4

{
  "name": "Asus Rog G15 G513RM",
  "description": "Republik Of Gammer",
  "price": 22000000,
  "quantity": 2,
  "category_id": 1,
  "supplier_id": 1
}

### FINDALL
GET http://localhost:3000/api/items
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiVXNlck5hbWUiOiJhZG1pbiIsImlzcyI6ImtvcmllYnJ1aCIsImV4cCI6MTczMzA3MTIwNn0.uBNmBOS3FeArKtLqe6tel9U-OrVb0PdocoausOyqzYQ

### SUMARY
GET http://localhost:3000/api/items/info
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiVXNlck5hbWUiOiJhZG1pbiIsImlzcyI6ImtvcmllYnJ1aCIsImV4cCI6MTczMzA3MTIwNn0.uBNmBOS3FeArKtLqe6tel9U-OrVb0PdocoausOyqzYQ

### FIND BY CONDITION
GET http://localhost:3000/api/items/condition?condition=under&threshold=4
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiVXNlck5hbWUiOiJhZG1pbiIsImlzcyI6ImtvcmllYnJ1aCIsImV4cCI6MTczMzA3MTIwNn0.uBNmBOS3FeArKtLqe6tel9U-OrVb0PdocoausOyqzYQ

### FIND BY CONDITION
GET http://localhost:3000/api/items/condition?condition=over&threshold=4
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiVXNlck5hbWUiOiJhZG1pbiIsImlzcyI6ImtvcmllYnJ1aCIsImV4cCI6MTczMzA3MTIwNn0.uBNmBOS3FeArKtLqe6tel9U-OrVb0PdocoausOyqzYQ

### FIND BY CONDITION
GET http://localhost:3000/api/items/condition?condition=equal&threshold=10
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiVXNlck5hbWUiOiJhZG1pbiIsImlzcyI6ImtvcmllYnJ1aCIsImV4cCI6MTczMzA3MTIwNn0.uBNmBOS3FeArKtLqe6tel9U-OrVb0PdocoausOyqzYQ


### FIND metric
GET http://localhost:3000/api/items/metric
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiVXNlck5hbWUiOiJhZG1pbiIsImlzcyI6ImtvcmllYnJ1aCIsImV4cCI6MTczMzA3MTIwNn0.uBNmBOS3FeArKtLqe6tel9U-OrVb0PdocoausOyqzYQ
### FIND REPORT BY CATEGORY
GET http://localhost:3000/api/items/category?category=Electronic
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiVXNlck5hbWUiOiJhZG1pbiIsImlzcyI6ImtvcmllYnJ1aCIsImV4cCI6MTczMzA3MTIwNn0.uBNmBOS3FeArKtLqe6tel9U-OrVb0PdocoausOyqzYQ