###
POST http://localhost:3000/api/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}

###
POST http://localhost:3000/api/suppliers
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiVXNlck5hbWUiOiJhZG1pbiIsImlzcyI6ImtvcmllYnJ1aCIsImV4cCI6MTczMzA3MTMzMH0.Azz-GVN_RztD3agp1M-8yBU0vOBSbsqHVNDUpJBPCX4

{
  "name": "d",
  "contact_info": "088385"
}



###
GET http://localhost:3000/api/suppliers
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiVXNlck5hbWUiOiJhZG1pbiIsImlzcyI6ImtvcmllYnJ1aCIsImV4cCI6MTczMzA3MTMzMH0.Azz-GVN_RztD3agp1M-8yBU0vOBSbsqHVNDUpJBPCX4

###
GET http://localhost:3000/api/suppliers/info
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiVXNlck5hbWUiOiJhZG1pbiIsImlzcyI6ImtvcmllYnJ1aCIsImV4cCI6MTczMzA3MTMzMH0.Azz-GVN_RztD3agp1M-8yBU0vOBSbsqHVNDUpJBPCX4